### ISSUE TITLE
Programme Start and Stop time attributes are incorrect and the same for all programs

### ISSUE THREAD

**Issue by tree-poplar-lurk** [dtankdempse/methstreams-m3u#1]
Looking at the most recent epg.xml I see:

```
  <programme start="20241127131339 +0000" stop="20241129131339 +0000" channel="6b976eeaa8a279cd24ccbd670e4bbade">
    <title>Notre Dame vs Houston - 12:30 AM EST - (11/28/2024)</title>
    <desc>09:30 PM PST / 10:30 PM MST / 12:30 AM EST
05:30 AM GMT / 06:30 AM CET / 01:30 PM CST</desc>
  </programme>
```

```
  <programme start="20241127131339 +0000" stop="20241129131339 +0000" channel="14ab765a0231e5f413b993c1a28f4004">
    <title>Charleston Southern vs Georgia Tech - 07:30 PM EST - (11/27/2024)</title>
    <desc>04:30 PM PST / 05:30 PM MST / 07:30 PM EST
12:30 AM GMT / 01:30 AM CET / 08:30 AM CST</desc>
  </programme>
```

```
  <programme start="20241127131339 +0000" stop="20241129131339 +0000" channel="9c1907f641c339e9abf4850f7cd80352">
    <title>South Dakota vs Nebraska - 06:30 PM EST - (11/27/2024)</title>
    <desc>03:30 PM PST / 04:30 PM MST / 06:30 PM EST
11:30 PM GMT / 12:30 AM CET / 07:30 AM CST</desc>
  </programme>
```

These are 3 programs with different times, but their start and stop attributes are the same.  Also, if I read these right, these programs are 2 days long!  That’s obviously not the case because the description says so.

**Comment by dtankdempse** [comment]
Since the streams are dynamic and do not play consecutively on a fixed channel, the EPG is set to begin at the current time and run for 48 hours, or until the playlist updates. This approach is intentional, allowing the program times to be displayed within the description, rather than just in the title, as you would typically see with an IPTV provider.

**Comment by tree-poplar-lurk** [comment]
BTW thank you for the good work making this and thank you again for the quick response!  I was checking out Napier, NZ and it looks awesome!!!

But I am wondering if starting the EPG at the current time and skipping the program details is really a good idea.  Even at the moment, hours before gametime, the stream (https://v14.thetvapp.to/hls/NBA01/index.m3u8?token=OTFEdlFwM0YyWlpvc25mOWtnVlhQaEJMbDFNb1RuMXJaYXlLdGdNMw==) is playing the spinning NBA logo.  The stream is going, maybe it was created sometime this morning and will die sometime tonight (whenever those times are).  If the program start and end times were accurate, users using The Channels App and DVR could discover and record the program.  As it is, Channels DVR is happy to record 48 hours of the show from whenever it downloads the EPG, most of which would be empty and I would have to go hunt for content.  But if the program data is published, the Channels DVR could catch the important bits during gametime.  

Is there a way to make this dynamic?  To allow people to have both options?  Or an option to customize it easily?
