### ISSUE TITLE
Catagorys/Genre

### ISSUE THREAD

**Issue by closernin7** [dtankdempse/methstreams-m3u#3]
Would it be possible to add a guide genre to each event to help with sorting.

Example:
tvc-guide-genres="Sports"

**Comment by dtankdempse** [comment]
I'll see what I can do about adding it.

**Comment by closernin7** [comment]
Awesome, this would help with guide data sorting in ChannelsDVR and Emby.  

Everything has been working great, really appreciate your efforts on creating this.

**Comment by dtankdempse** [comment]
Good thing you replied here. It completely slipped my mind. I'll add it today.

**Comment by dtankdempse** [comment]
This has be added.

**Comment by closernin7** [comment]
Your're awesome!  My fault, I should have looked at where the data needs to be.  I think it needs to be in the Guide XML.  

![Screenshot 2024-12-11 181907](https://github.com/user-attachments/assets/197b3567-2695-403a-8f83-e98be8611813)

I attached a screenshot from the guide data in ChannelsDVR.  I think it can be done th eway you did it in the M3U or by the category call.  If its to much trouble all good.

**Comment by dtankdempse** [comment]
No trouble, one line of code was all that was needed. It should be included in the EPG data now.

**Comment by closernin7** [comment]
That worked, You're Awesome!!  Really appreicate it.
